
spring:
  profiles: dev # 开发环境 
  application:   
    name: microservice-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个 name
  datasource:
    url: jdbc:mysql://192.168.31.213:3306/springcloud_db01
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5       # 数据库连接池的最小维持连接数

      initial-size: 5
      max-total: 5
      max-wait-millis: 150

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml # mapper映射文件
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.mengxuegu.springcloud.entities # 所有Entity别名类所在包
server:
  port: 8001

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
     #单机
      #defaultZone: http://localhost:6001/eureka
    #集群
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/,
  instance:
    instance-id: ${spring.application.name}:${server.port} #等价于microservice-product：8001
    ip-address: true
